import logging
import os

from dotenv import load_dotenv

load_dotenv()

CRLF = "\r\n"
MISP_API_URL = os.environ.get("MISP_API_URL")
MISP_API_KEY = os.environ.get("MISP_API_KEY")
NATS_URL = os.environ.get("NATS_URL")
SUBSCRIBE_SUBJECT = os.environ.get("SUBSCRIBE_SUBJECT")
SUBSCRIBE_QUEUE = os.environ.get("SUBSCRIBE_QUEUE")
if os.environ.get("MISP_CERTIFICATE_VERIFY").lower() in ["true", "1"]:
    MISP_CERTIFICATE_VERIFY = True
else:
    MISP_CERTIFICATE_VERIFY = False
LOG_FILE = os.environ.get("LOG_FILE", "misp_client.log")
log_format = logging.Formatter(
    "[%(asctime)s %(levelname)s] %(message)s", "%d-%m-%Y %H:%M:%S"
)

MISP_ECS_ATTRIBUTES_MAP = {
    # ECS attribute: MISP attribute
    "asn": "AS",
    "ip": "ip-src",
    "@timestamp": "datetime",
    # "": "aba-rtn",
    # "": "anonymised",
    # "": "attachment",
    # "": "authentihash",
    # "": "bank-account-nr",
    # "": "bic",
    # "": "bin",
    # "": "boolean",
    # "": "bro",
    # "": "btc",
    # "": "campaign-id",
    # "": "campaign-name",
    # "": "cc-number",
    # "": "cdhash",
    # "": "chrome-extension-id",
    # "": "comment",
    # "": "community-id",
    # "": "cookie",
    # "": "cortex",
    # "": "counter",
    # "": "country-of-residence",
    # "": "cpe",
    # "": "dash",
    # "": "date-of-birth",
    # "": "dkim",
    # "": "dkim-signature",
    # "": "dns-soa-email",
    # "": "domain",
    # "": "domain|ip",
    # "": "email",
    # "": "email-attachment",
    # "": "email-body",
    # "": "email-dst",
    # "": "email-dst-display-name",
    # "": "email-header",
    # "": "email-message-id",
    # "": "email-mime-boundary",
    # "": "email-reply-to",
    # "": "email-src",
    # "": "email-src-display-name",
    # "": "email-subject",
    # "": "email-thread-index",
    # "": "email-x-mailer",
    # "": "eppn",
    # "": "favicon-mmh3",
    # "": "filename",
    # "": "filename-pattern",
    # "": "filename|authentihash",
    # "": "filename|impfuzzy",
    # "": "filename|imphash",
    # "": "filename|md5",
    # "": "filename|pehash",
    # "": "filename|sha1",
    # "": "filename|sha224",
    # "": "filename|sha256",
    # "": "filename|sha3-224",
    # "": "filename|sha3-256",
    # "": "filename|sha3-384",
    # "": "filename|sha3-512",
    # "": "filename|sha384",
    # "": "filename|sha512",
    # "": "filename|sha512/224",
    # "": "filename|sha512/256",
    # "": "filename|ssdeep",
    # "": "filename|tlsh",
    # "": "filename|vhash",
    # "": "first-name",
    # "": "float",
    # "": "frequent-flyer-number",
    # "": "full-name",
    # "": "gender",
    # "": "gene",
    # "": "git-commit-id",
    # "": "github-organisation",
    # "": "github-repository",
    # "": "github-username",
    # "": "hassh-md5",
    # "": "hasshserver-md5",
    # "": "hex",
    # "": "hostname",
    # "": "hostname|port",
    # "": "http-method",
    # "": "iban",
    # "": "identity-card-number",
    # "": "impfuzzy",
    # "": "imphash",
    # "": "ip-dst",
    # "": "ip-dst|port",
    # "": "ip-src|port",
    # "": "issue-date-of-the-visa",
    # "": "ja3-fingerprint-md5",
    # "": "jabber-id",
    # "": "jarm-fingerprint",
    # "": "kusto-query",
    # "": "last-name",
    # "": "link",
    # "": "mac-address",
    # "": "mac-eui-64",
    # "": "malware-sample",
    # "": "malware-type",
    # "": "md5",
    # "": "middle-name",
    # "": "mime-type",
    # "": "mobile-application-id",
    # "": "mutex",
    # "": "named pipe",
    # "": "nationality",
    # "": "other",
    # "": "passenger-name-record-locator-number",
    # "": "passport-country",
    # "": "passport-expiration",
    # "": "passport-number",
    # "": "pattern-in-file",
    # "": "pattern-in-memory",
    # "": "pattern-in-traffic",
    # "": "payment-details",
    # "": "pdb",
    # "": "pehash",
    # "": "pgp-private-key",
    # "": "pgp-public-key",
    # "": "phone-number",
    # "": "place-of-birth",
    # "": "place-port-of-clearance",
    # "": "place-port-of-onward-foreign-destination",
    # "": "place-port-of-original-embarkation",
    # "": "port",
    # "": "primary-residence",
    # "": "process-state",
    # "": "prtn",
    # "": "redress-number",
    # "": "regkey",
    # "": "regkey|value",
    # "": "sha1",
    # "": "sha224",
    # "": "sha256",
    # "": "sha3-224",
    # "": "sha3-256",
    # "": "sha3-384",
    # "": "sha3-512",
    # "": "sha384",
    # "": "sha512",
    # "": "sha512/224",
    # "": "sha512/256",
    # "": "sigma",
    # "": "size-in-bytes",
    # "": "snort",
    # "": "special-service-request",
    # "": "ssdeep",
    # "": "ssh-fingerprint",
    # "": "stix2-pattern",
    # "": "target-email",
    # "": "target-external",
    # "": "target-location",
    # "": "target-machine",
    # "": "target-org",
    # "": "target-user",
    # "": "telfhash",
    # "": "text",
    # "": "threat-actor",
    # "": "tlsh",
    # "": "travel-details",
    # "": "twitter-id",
    # "": "uri",
    # "": "url",
    # "": "user-agent",
    # "": "vhash",
    # "": "visa-number",
    # "": "vulnerability",
    # "": "weakness",
    # "": "whois-creation-date",
    # "": "whois-registrant-email",
    # "": "whois-registrant-name",
    # "": "whois-registrant-org",
    # "": "whois-registrant-phone",
    # "": "whois-registrar",
    # "": "windows-scheduled-task",
    # "": "windows-service-displayname",
    # "": "windows-service-name",
    # "": "x509-fingerprint-md5",
    # "": "x509-fingerprint-sha1",
    # "": "x509-fingerprint-sha256",
    # "": "xmr",
    # "": "yara",
    # "": "zeek",
}

MISP_ATTRIBUTES_CATEGORIES = [
    "Internal reference",
    "Targeting data",
    "Antivirus detection",
    "Payload delivery",
    "Artifacts dropped",
    "Payload installation",
    "Persistence mechanism",
    "Network activity",
    "Payload type",
    "Attribution",
    "External analysis",
    "Financial fraud",
    "Support Tool",
    "Social network",
    "Person",
    "Other",
]

MISP_ATTRIBUTES_CATEGORIES_TYPES_MAP = {
    "Internal reference": [
        "text",
        "link",
        "comment",
        "other",
        "hex",
        "anonymised",
        "git-commit-id",
    ],
    "Targeting data": [
        "target-user",
        "target-email",
        "target-machine",
        "target-org",
        "target-location",
        "target-external",
        "comment",
        "anonymised",
    ],
    "Antivirus detection": [
        "link",
        "comment",
        "text",
        "hex",
        "attachment",
        "other",
        "anonymised",
    ],
    "Payload delivery": [
        "md5",
        "sha1",
        "sha224",
        "sha256",
        "sha384",
        "sha512",
        "sha512/224",
        "sha512/256",
        "sha3-224",
        "sha3-256",
        "sha3-384",
        "sha3-512",
        "ssdeep",
        "imphash",
        "telfhash",
        "impfuzzy",
        "authentihash",
        "vhash",
        "pehash",
        "tlsh",
        "cdhash",
        "filename",
        "filename|md5",
        "filename|sha1",
        "filename|sha224",
        "filename|sha256",
        "filename|sha384",
        "filename|sha512",
        "filename|sha512/224",
        "filename|sha512/256",
        "filename|sha3-224",
        "filename|sha3-256",
        "filename|sha3-384",
        "filename|sha3-512",
        "filename|authentihash",
        "filename|vhash",
        "filename|ssdeep",
        "filename|tlsh",
        "filename|imphash",
        "filename|impfuzzy",
        "filename|pehash",
        "mac-address",
        "mac-eui-64",
        "ip-src",
        "ip-dst",
        "ip-dst|port",
        "ip-src|port",
        "hostname",
        "domain",
        "email",
        "email-src",
        "email-dst",
        "email-subject",
        "email-attachment",
        "email-body",
        "url",
        "user-agent",
        "AS",
        "pattern-in-file",
        "pattern-in-traffic",
        "filename-pattern",
        "stix2-pattern",
        "yara",
        "sigma",
        "mime-type",
        "attachment",
        "malware-sample",
        "link",
        "malware-type",
        "comment",
        "text",
        "hex",
        "vulnerability",
        "cpe",
        "weakness",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "ja3-fingerprint-md5",
        "jarm-fingerprint",
        "hassh-md5",
        "hasshserver-md5",
        "other",
        "hostname|port",
        "email-dst-display-name",
        "email-src-display-name",
        "email-header",
        "email-reply-to",
        "email-x-mailer",
        "email-mime-boundary",
        "email-thread-index",
        "email-message-id",
        "mobile-application-id",
        "chrome-extension-id",
        "whois-registrant-email",
        "anonymised",
    ],
    "Artifacts dropped": [
        "md5",
        "sha1",
        "sha224",
        "sha256",
        "sha384",
        "sha512",
        "sha512/224",
        "sha512/256",
        "sha3-224",
        "sha3-256",
        "sha3-384",
        "sha3-512",
        "ssdeep",
        "imphash",
        "telfhash",
        "impfuzzy",
        "authentihash",
        "vhash",
        "cdhash",
        "filename",
        "filename|md5",
        "filename|sha1",
        "filename|sha224",
        "filename|sha256",
        "filename|sha384",
        "filename|sha512",
        "filename|sha512/224",
        "filename|sha512/256",
        "filename|sha3-224",
        "filename|sha3-256",
        "filename|sha3-384",
        "filename|sha3-512",
        "filename|authentihash",
        "filename|vhash",
        "filename|ssdeep",
        "filename|tlsh",
        "filename|imphash",
        "filename|impfuzzy",
        "filename|pehash",
        "regkey",
        "regkey|value",
        "pattern-in-file",
        "pattern-in-memory",
        "filename-pattern",
        "pdb",
        "stix2-pattern",
        "yara",
        "sigma",
        "attachment",
        "malware-sample",
        "named pipe",
        "mutex",
        "process-state",
        "windows-scheduled-task",
        "windows-service-name",
        "windows-service-displayname",
        "comment",
        "text",
        "hex",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "other",
        "cookie",
        "gene",
        "kusto-query",
        "mime-type",
        "anonymised",
        "pgp-public-key",
        "pgp-private-key",
    ],
    "Payload installation": [
        "md5",
        "sha1",
        "sha224",
        "sha256",
        "sha384",
        "sha512",
        "sha512/224",
        "sha512/256",
        "sha3-224",
        "sha3-256",
        "sha3-384",
        "sha3-512",
        "ssdeep",
        "imphash",
        "telfhash",
        "impfuzzy",
        "authentihash",
        "vhash",
        "pehash",
        "tlsh",
        "cdhash",
        "filename",
        "filename|md5",
        "filename|sha1",
        "filename|sha224",
        "filename|sha256",
        "filename|sha384",
        "filename|sha512",
        "filename|sha512/224",
        "filename|sha512/256",
        "filename|sha3-224",
        "filename|sha3-256",
        "filename|sha3-384",
        "filename|sha3-512",
        "filename|authentihash",
        "filename|vhash",
        "filename|ssdeep",
        "filename|tlsh",
        "filename|imphash",
        "filename|impfuzzy",
        "filename|pehash",
        "pattern-in-file",
        "pattern-in-traffic",
        "pattern-in-memory",
        "filename-pattern",
        "stix2-pattern",
        "yara",
        "sigma",
        "vulnerability",
        "cpe",
        "weakness",
        "attachment",
        "malware-sample",
        "malware-type",
        "comment",
        "text",
        "hex",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "mobile-application-id",
        "chrome-extension-id",
        "other",
        "mime-type",
        "anonymised",
    ],
    "Persistence mechanism": [
        "filename",
        "regkey",
        "regkey|value",
        "comment",
        "text",
        "other",
        "hex",
        "anonymised",
    ],
    "Network activity": [
        "ip-src",
        "ip-dst",
        "ip-dst|port",
        "ip-src|port",
        "port",
        "hostname",
        "domain",
        "domain|ip",
        "mac-address",
        "mac-eui-64",
        "email",
        "email-dst",
        "email-src",
        "eppn",
        "url",
        "uri",
        "user-agent",
        "http-method",
        "AS",
        "snort",
        "pattern-in-file",
        "filename-pattern",
        "stix2-pattern",
        "pattern-in-traffic",
        "attachment",
        "comment",
        "text",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha1",
        "x509-fingerprint-sha256",
        "ja3-fingerprint-md5",
        "jarm-fingerprint",
        "hassh-md5",
        "hasshserver-md5",
        "other",
        "hex",
        "cookie",
        "hostname|port",
        "bro",
        "zeek",
        "anonymised",
        "community-id",
        "email-subject",
        "favicon-mmh3",
        "dkim",
        "dkim-signature",
        "ssh-fingerprint",
    ],
    "Payload type": ["comment", "text", "other", "anonymised"],
    "Attribution": [
        "threat-actor",
        "campaign-name",
        "campaign-id",
        "whois-registrant-phone",
        "whois-registrant-email",
        "whois-registrant-name",
        "whois-registrant-org",
        "whois-registrar",
        "whois-creation-date",
        "comment",
        "text",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "other",
        "dns-soa-email",
        "anonymised",
        "email",
    ],
    "External analysis": [
        "md5",
        "sha1",
        "sha256",
        "sha3-224",
        "sha3-256",
        "sha3-384",
        "sha3-512",
        "filename",
        "filename|md5",
        "filename|sha1",
        "filename|sha256",
        "filename|sha3-224",
        "filename|sha3-256",
        "filename|sha3-384",
        "filename|sha3-512",
        "ip-src",
        "ip-dst",
        "ip-dst|port",
        "ip-src|port",
        "mac-address",
        "mac-eui-64",
        "hostname",
        "domain",
        "domain|ip",
        "url",
        "user-agent",
        "regkey",
        "regkey|value",
        "AS",
        "snort",
        "bro",
        "zeek",
        "pattern-in-file",
        "pattern-in-traffic",
        "pattern-in-memory",
        "filename-pattern",
        "vulnerability",
        "cpe",
        "weakness",
        "attachment",
        "malware-sample",
        "link",
        "comment",
        "text",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "ja3-fingerprint-md5",
        "jarm-fingerprint",
        "hassh-md5",
        "hasshserver-md5",
        "github-repository",
        "other",
        "cortex",
        "anonymised",
        "community-id",
    ],
    "Financial fraud": [
        "btc",
        "dash",
        "xmr",
        "iban",
        "bic",
        "bank-account-nr",
        "aba-rtn",
        "bin",
        "cc-number",
        "prtn",
        "phone-number",
        "comment",
        "text",
        "other",
        "hex",
        "anonymised",
    ],
    "Support Tool": [
        "link",
        "text",
        "attachment",
        "comment",
        "other",
        "hex",
        "anonymised",
    ],
    "Social network": [
        "github-username",
        "github-repository",
        "github-organisation",
        "jabber-id",
        "twitter-id",
        "email",
        "email-src",
        "email-dst",
        "eppn",
        "comment",
        "text",
        "other",
        "whois-registrant-email",
        "anonymised",
        "pgp-public-key",
        "pgp-private-key",
    ],
    "Person": [
        "first-name",
        "middle-name",
        "last-name",
        "full-name",
        "date-of-birth",
        "place-of-birth",
        "gender",
        "passport-number",
        "passport-country",
        "passport-expiration",
        "redress-number",
        "nationality",
        "visa-number",
        "issue-date-of-the-visa",
        "primary-residence",
        "country-of-residence",
        "special-service-request",
        "frequent-flyer-number",
        "travel-details",
        "payment-details",
        "place-port-of-original-embarkation",
        "place-port-of-clearance",
        "place-port-of-onward-foreign-destination",
        "passenger-name-record-locator-number",
        "comment",
        "text",
        "other",
        "phone-number",
        "identity-card-number",
        "anonymised",
        "email",
        "pgp-public-key",
        "pgp-private-key",
    ],
    "Other": [
        "comment",
        "text",
        "other",
        "size-in-bytes",
        "counter",
        "datetime",
        "cpe",
        "port",
        "float",
        "hex",
        "phone-number",
        "boolean",
        "anonymised",
        "pgp-public-key",
        "pgp-private-key",
    ],
}
